spring.application.name=gamestore

# Database configuration
spring.datasource.url=jdbc:postgresql://dpg-d6tvgg1aae7s73e6pme0-a.oregon-postgres.render.com/db_deploy_gs_joaogpessoa6-spec
spring.datasource.username=db_deploy_gs_joaogpessoa6-spec
spring.datasource.password=${DB_PASSWORD}

# JPA configuration
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect